name: pokeapp
description: A Flutter application to showcase Pokémon.
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  flutter_bloc: ^8.0.0
  url_launcher: ^6.0.20 # Asegúrate de usar la última versión
  google_maps_flutter: ^2.1.1

  



dev_dependencies:
  flutter_lints: ^5.0.0  # Mantener esta versión
  leak_tracker: ^10.0.7
  leak_tracker_flutter_testing: ^3.0.8


flutter:
  uses-material-design: true
  fonts:
    - family: Chakra Petch
      fonts:
        - asset: lib/assets/fonts/ChakraPetch-Regular.ttf
        - asset: lib/assets/fonts/ChakraPetch-Bold.ttf


  assets:
    - lib/assets/images/
    - lib/widgets/

